name: Build and Test RESTful PiggyBank Microservice

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
              distribution: 'temurin'
              java-version: '21'

      - name: Execute Gradle Build
        run: ./gradlew build

      - name: Build the Docker Image
        run: docker build . -t piggybankmicro

      - name: Run the Docker Container
        run: docker run -d -p 8080:8080 piggybankmicro

      - name: Test the RESTful service
        run: |
          # Wait for the container to start up
          sleep 30
          
          # Send GET and Request Mapping request to the service.
          response_default=$(curl http://localhost:8080)
          response_fib=$(curl http://localhost:8080/fib?length=18)
          response_total=$(curl http://localhost:8080/totalMoney)
          
          
          # Check all outputs to ensure they match what is expected.
          if [ "$response_default" == "Hello." ]; then
            echo "Default Test passed!"
          else
            echo "Default Test failed. Expected 'Hello.', got '$response_default'"
            exit 1
          fi


          if [ "$response_fib" == "[0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597]" ]; then
            echo "Fibonacci test passed!"
          else
            echo "Fibonacci test failed. Expected '[0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597]', got '$response_fib'"
            exit 1
          fi

          if [ "$response_total" == "You have $0.0 in the Piggy Bank." ]; then
            echo "TotalMoney test passed!"
          else
            echo "TotalMoney test failed. Expected 'You have: $0.0 in the Piggy Bank.', got '$response_total'"
            exit 1
          fi